#!/usr/bin/env bash
# Write the qwen-code workspace config files into <dest>/.qwen/.
# Usage: bash scripts/workspace/configure.sh <dest> <backend> <served> <sandbox>
# Requires: HOST and APIKEY env vars (set via eval of scripts/lib/backend.sh)
set -euo pipefail
dest="${1:?dest required}"
backend="${2:?backend required}"
served="${3:?served required}"
sandbox="${4:-true}"
host="${HOST:?HOST env var required (eval scripts/lib/backend.sh first)}"
apikey="${APIKEY:?APIKEY env var required (eval scripts/lib/backend.sh first)}"

MARKER="$dest/.qwen/.bootstrapped"

mkdir -p "$dest/.qwen"

# Refuse to clobber config that was not written by this tool.
if { [ -f "$dest/.qwen/.env" ] || [ -f "$dest/.qwen/settings.json" ]; } \
   && [ ! -f "$MARKER" ]; then
  echo "error: $dest/.qwen/ already contains config not generated by this bootstrapper." >&2
  echo "       To replace it, delete $dest/.qwen/.env and $dest/.qwen/settings.json first." >&2
  exit 1
fi

cat > "$dest/.qwen/.env" <<ENV
# Local $backend provider for qwen-code (OpenAI-compatible API)
OPENAI_BASE_URL=$host/v1
OPENAI_API_KEY=$apikey
OPENAI_MODEL=$served
ENV

cat > "$dest/.qwen/settings.json" <<JSON
{
  "security": { "auth": { "selectedType": "openai" } },
  "privacy": { "usageStatisticsEnabled": false },
  "telemetry": { "enabled": false, "logPrompts": false },
  "general": { "enableAutoUpdate": false },
  "tools": { "approvalMode": "default", "sandbox": $sandbox },
  "mcpServers": {}
}
JSON

echo "generated-by-dev-bootstrap-local-coding-agents" > "$MARKER"

if [ ! -f "$dest/QWEN.md" ]; then
  cat > "$dest/QWEN.md" <<MD
# Project context for qwen-code

This workspace runs a **local** coding agent served by $backend
(model: $served) through the OpenAI-compatible endpoint at $host/v1.

## Conventions
- Keep changes minimal and scoped to the request.
- Prefer running and verifying changes over assuming success.
- Ask before destructive or wide-reaching actions.
MD
else
  echo "⚠ $dest/QWEN.md already exists — skipped (delete to regenerate)" >&2
fi
echo "✓ wrote $dest/.qwen/.env, $dest/.qwen/settings.json"
